### ISSUE TITLE
'ConfigDict' object has no attribute 'device'

### ISSUE THREAD

**Issue by jongwoopark7978** [WangYueFt/detr3d#43]
Hi,

I run train.py and get the error below

**`tools/dist_train.sh /home_shared/jongwoo/detr3d/projects/configs/detr3d/detr3d_res101_gridmask.py 8`**

`Traceback (most recent call last):
  File "tools/train.py", line 248, in <module>
    main()
  File "tools/train.py", line 237, in main
    train_model(
  File "/home_shared/jongwoo/detr3d/mmdetection3d/mmdet3d/apis/train.py", line 28, in train_model
    train_detector(
  File "/home_shared/jongwoo/miniconda3/envs/cuda11_1/lib/python3.8/site-packages/mmdet/apis/train.py", line 158, in train_detector
    cfg.device,
  File "/home_shared/jongwoo/miniconda3/envs/cuda11_1/lib/python3.8/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
**AttributeError: 'ConfigDict' object has no attribute 'device'`**

**I am using Ubuntu 18.04.5 LTS and I train with a single node and 8 GPUs. This device issue happens only when I run training.**

I can run dist_test.sh without any problem. I can successfully run the following code.

`nohup tools/dist_test.sh /home_shared/jongwoo/detr3d/projects/configs/detr3d/detr3d_res101_gridmask.py /home_shared/jongwoo/detr3d/pretrain_weight/detr3d_resnet101.pth 8 --eval=bbox &`

**Comment by SilverAlbum** [comment]
Hi. I meet the same problem and I solve it by degrade mmdet from 2.24.0 to 2.14.0.
It seems like the incompatibility of mmdet version
